// Punto de entrada de la API: tipos y hooks de TanStack Query por dominio.
// Los tipos reflejan los DTOs de backend/src/Wan.Api/Controllers: mantenerlos sincronizados.
export * from '@/services/api/auth'
export * from '@/services/api/account'
export * from '@/services/api/extensions'
export * from '@/services/api/calls'
export * from '@/services/api/campaigns'
export * from '@/services/api/analytics'
export * from '@/services/api/audit'
export * from '@/services/api/ai'
export * from '@/services/api/directory'
export * from '@/services/api/forms'
export * from '@/services/api/messages'
export * from '@/services/api/recordings'
export * from '@/services/api/settings'
export * from '@/services/api/knowledge'
export * from '@/services/api/tools'
export * from '@/services/api/users'
export { ApiError, api } from '@/services/api/client'
